name = "MyPkg"
uuid = "b59f1ed4-4c8e-4fc7-a035-90d7cbd7aaf3"
authors = ["Carlos Castillo Passi <cncastillo@uc.cl>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.11.0"
