name: Run Tests and Benchmarks

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  statuses: read
  deployments: write
  pull-requests: write

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [lts]
        arch: [x64]

    continue-on-error: false
    
    steps:
      # Step 0: Setup environment
      - uses: actions/checkout@v4

      - name: "Setup Julia ${{ matrix.version }}"
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - uses: julia-actions/cache@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
      
      - uses: julia-actions/julia-buildpkg@v1
      
      # Step 1: Run tests
      - name: Run tests
        uses: julia-actions/julia-runtest@v1
      
      # Step 2: Install benchmark dependencies
      - name: Install dependencies
        run: julia --project=benchmarks/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'

      # Step 3: Run the benchmarks
      - name: Run benchmarks
        run: julia --project=benchmarks benchmarks/benchmark.jl

      # Step 4: Upload benchmark results using github-action-benchmark
      - name: Upload Benchmark Results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Julia benchmark result
          tool: 'julia'
          output-file-path: benchmarks/benchmark_results.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          comment-on-alert: true
          fail-on-alert: true

      # Step 5: Upload the benchmark results as a check on GitHub
      - name: Upload benchmark results to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results
          path: benchmarks/benchmark_results.json